### PR TITLE
Upgraded dependencies.

### PR DESCRIPTION
**Pull request by jreniel**
Ran cargo update && cargo upgrade && cargo add gdal-sys --features=bindgen to be able to compile with latest gdal.

### CODE REVIEW

**Comment by rmanoka** [comment]
Looks great; thanks!  We don't have github CI here yet.  Will check it offline, and merge this

**Comment by jreniel** [comment]
Thanks for keeping this repo up!
I'm slowly working through it but I need things like windowed raster band iterations, and that sort.
Thanks for sharing this code!

**Comment by rmanoka** [comment]
Could you make the bindgen an optional feature on this crate, and connect to gdal-sys/bindgen flag?  With your PR, users won't be able to not use bindgen.

**Comment by jreniel** [comment]
> Could you make the bindgen an optional feature on this crate, and connect to gdal-sys/bindgen flag? With your PR, users won't be able to not use bindgen.

Good point, let me fix that...

**Comment by jreniel** [comment]
Hi @rmanoka,
I've simply added `optional = true` for gdal-sys. I suppose that any person adding gdal-sys explicitly is because they're looking for bindgen, otherwise, they wouldn't be overriding gdal-sys.

When it comes to features in Cargo.toml, I'm still a newbie, so I'm guessing there's no point to have separate flags for gdal-sys vs gdal-sys with bindgen. So I assume anyone adding gdal-sys as a feature is because they need bindgen.

Thanks!

**Comment by rmanoka** [comment]
That seems fine;  gdal-sys doesn't seem to have other features, atleast rn.  I'll try to merge and publish this week.  Thanks agian!

**Review by rmanoka — APPROVED** [review]

**Pull request merged**
